### ISSUE TITLE
Alignwide and full without transform

### ISSUE THREAD

**Issue by davidsword** [ArrayHQ/atomic-blocks-theme#11]
Thank you for this theme, it's great.

I had some troubles with a `alignwide` gallery, the `transform -50%` took the gallery off screen (on a 1440px wide monitor).

Instead of setting a primary wrapper/container with the width, and transforming alignwide/full out of it, why not set the container to be full width, then set the blocks width instead?

Here's some overwriting CSS appended to site that fixed the issue for me:

```css
html #page {
	max-width: 100%;
	padding-left: 0;
	padding-right: 0;
	width: auto;
}
html #primary {
	width: auto;
}
html .entry-content > * {
	margin-left: auto;
	margin-right: auto;
	max-width: 90%;
	width: 780px;
}
html .entry-content > .alignwide {
	max-width: 90%;
	transform: none !important;
	width: 1440px;
}
html .entry-content > .alignfull {
	max-width:100%;
	transform: none !important;
	width: auto;
}
```

I know this doesn't factor in the "set width" setting in Customizer, this is my use case and just for a code-example.

Again, great theme, thank you so much for making and releasing it.
